
TABLE_SCHEMAS = {
    "users": {
        "id": int,
        "username": str,
        "created_at": str,
    },
    "assessments": {
        "id": int,
        "user_id": int,
        "date": str,
        "monthly_income": float,
        "savings_percentage": float,
        "emergency_fund": str,
        "funds_invested": str,
        "investment_type": str,
        "expected_return": float,
        "monthly_variance": float,
        "has_loans": str,
        "monthly_loan_payment": float,
        "outstanding_loan": float,
        "score": float,
        "region_code": str,
        "currency_data": str,
    },
    # "budget_categories": {
    #     "id": int,
    #     "assessment_id": int,
    #     "housing": float,
    #     "transportation": float,
    #     "food": float,
    #     "utilities": float,
    #     "healthcare": float,
    #     "entertainment": float,
    #     "personal": float,
    #     "other": float,
    # },
    # "goals": {
    #     "id": int,
    #     "user_id": int,
    #     "goal_name": str,
    #     "goal_amount": float,
    #     "current_amount": float,
    #     "target_date": str,
    #     "created_at": str,
    #     "region_code": str,
    #     "currency_symbol": str,
    # }
}
