TABLE_SCHEMAS = {
    "users": {
        "id": int,
        "username": str,
        "created_at": str,
    },
    "assessments": {
        "id": int,
        "user_id": int,
        "date": str,
        "monthly_income": float,
        "savings_percentage": float,
        "emergency_fund": str,
        "funds_invested": str,
        "investment_type": str,
        "expected_return": float,
        "monthly_variance": float,
        "has_loans": str,
        "monthly_loan_payment": float,
        "outstanding_loan": float,
        "score": float,
        "region_code": str,
        "currency_data": str,
    },
}